package ilevelin.ileuhc.utils.enums;

public enum AppleType {

    GOLDEN_APPLE,
    WITHER_APPLE,
    PLAYER_HEAD_APPLE,
    SUPER_GOLD_APPLE,
    DIAMOND_APPLE,
    BLUE_GOLD_APPLE,
    ROYAL_APPLE,
    ALLOYED_APPLE,
    MIDAS_APPLE,
    GOD_APPLE,
    COLLECTOR_APPLE,
    ENCHANTED_GOLDEN_APPLE

}
